packageExtensions:
  "@arkecosystem/core-database@*":
    dependencies:
      "pg": "latest"
  "@arkecosystem/core-kernel@*":
    dependencies:
      "@arkecosystem/core-api": "next"
      "@arkecosystem/core-blockchain": "next"
      "@arkecosystem/core-database": "next"
      "@arkecosystem/core-forger": "next"
      "@arkecosystem/core-logger-pino": "next"
      "@arkecosystem/core-magistrate-api": "next"
      "@arkecosystem/core-magistrate-transactions": "next"
      "@arkecosystem/core-manager": "next"
      "@arkecosystem/core-p2p": "next"
      "@arkecosystem/core-snapshots": "next"
      "@arkecosystem/core-state": "next"
      "@arkecosystem/core-transaction-pool": "next"
      "@arkecosystem/core-transactions": "next"
      "@arkecosystem/core-webhooks": "next"
      "@protokol/guardian-api": "workspace:packages/guardian-api"
      "@protokol/guardian-transactions": "workspace:packages/guardian-transactions"
      "@protokol/nft-base-api": "beta"
      "@protokol/nft-base-transactions": "beta"
      "@protokol/nft-exchange-api": "beta"
      "@protokol/nft-exchange-transactions": "beta"
  "@arkecosystem/core-transaction-pool@*":
    dependencies:
      "@arkecosystem/core-magistrate-crypto": "next"
  "@arkecosystem/crypto@*":
    dependencies:
      "@types/node": "latest"
  "@arkecosystem/core@*":
    dependencies:
      "@oclif/errors": "latest"
  "@protokol/nft-base-transactions@*":
    dependencies:
      "ajv": "latest"
  "@protokol/nft-exchange-api@*":
    dependencies:
      "@protokol/nft-exchange-crypto": "beta"
  "@types/eslint-plugin-prettier@*":
    dependencies:
      "eslint": "latest"
  "node-fetch@*":
    dependencies:
      "domexception": "latest"
  "pg-cursor@*":
    dependencies:
      "pg": "latest"
  "typeorm@*":
    dependencies:
      "pg": "latest"
      "pg-query-stream": "latest"
  "@oclif/plugin-help@*":
    dependencies:
      "@oclif/errors": "latest"


plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-2.3.3.cjs
