packageExtensions:
  "@arkecosystem/core-kernel@*":
    dependencies:
      "@arkecosystem/core-api": latest
      "@arkecosystem/core-blockchain": latest
      "@arkecosystem/core-database": latest
      "@arkecosystem/core-forger": latest
      "@arkecosystem/core-logger-pino": latest
      "@arkecosystem/core-magistrate-api": latest
      "@arkecosystem/core-magistrate-transactions": latest
      "@arkecosystem/core-p2p": latest
      "@arkecosystem/core-snapshots": latest
      "@arkecosystem/core-state": latest
      "@arkecosystem/core-transaction-pool": latest
      "@arkecosystem/core-transactions": latest
      "@arkecosystem/core-webhooks": latest
      "@protokol/guardian-api": "workspace:packages/guardian-api"
      "@protokol/guardian-transactions": "workspace:packages/guardian-transactions"
  "@arkecosystem/core-magistrate-api@*":
    dependencies:
      "@arkecosystem/crypto": latest
  "@arkecosystem/core-manager@*":
    dependencies:
      lodash: latest
  "@arkecosystem/core-snapshots@*":
    dependencies:
      joi: latest
  "@arkecosystem/core-transaction-pool@*":
    dependencies:
      "@arkecosystem/core-magistrate-crypto": next
  "@arkecosystem/core@*":
    dependencies:
      "@oclif/errors": latest
  "@arkecosystem/crypto@*":
    dependencies:
      "@types/node": latest
  "@types/eslint-plugin-prettier@*":
    dependencies:
      eslint: latest
  jest-circus@*:
    dependencies:
      slash: 3.0.0
  jest-util@*:
    dependencies:
      jest-runner: latest
  node-fetch@*:
    dependencies:
      domexception: latest
  pg-cursor@*:
    dependencies:
      pg: latest
  typeorm@*:
    dependencies:
      pg: latest
      pg-query-stream: latest

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.0.2.cjs
