name: UNIT-TESTS

on:
    push:
        branches:
            - "master"
            - "develop"
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
    unit:
        name: UNIT (API, CRYPTO, TRANSACTIONS)
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install And Build
              run: yarn && yarn build

            - name: GUARDIAN-CRYPTO
              run: cd packages/guardian-crypto && yarn test:unit:coverage --maxWorkers=2

            - uses: codecov/codecov-action@v2
              with:
                directory: packages/guardian-crypto/.coverage
                flags: guardian-crypto

            - name: GUARDIAN-TRANSACTIONS
              run: cd packages/guardian-transactions && yarn test:unit:coverage --maxWorkers=2

            - uses: codecov/codecov-action@v2
              with:
                directory: packages/guardian-transactions/.coverage
                flags: guardian-transactions

            - name: GUARDIAN-API
              run: cd packages/guardian-api && yarn test:unit:coverage --maxWorkers=2

            - uses: codecov/codecov-action@v2
              with:
                directory: packages/guardian-api/.coverage
                flags: guardian-api
